import api from './axiosInstance';

export const getDashboardStats = () => api.get('/dashboard/stats');
export const getAssets = (params) => api.get('/assets', { params });
export const getAssetById = (id) => api.get(`/assets/${id}`);
export const createAsset = (data) => api.post('/assets', data);
export const updateAsset = (id, data) => api.patch(`/assets/${id}`, data);
export const updateAssetStatus = (id, data) => api.patch(`/assets/${id}/status`, data);
export const getAssetHistory = (id) => api.get(`/assets/${id}/history`);
export const getDepartments = (params) => api.get('/departments', { params });
export const createDepartment = (data) => api.post('/departments', data);
export const updateDepartment = (id, data) => api.patch(`/departments/${id}`, data);
export const deactivateDepartment = (id) => api.patch(`/departments/${id}/deactivate`);
export const getCategories = (params) => api.get('/asset-categories', { params });
export const createCategory = (data) => api.post('/asset-categories', data);
export const updateCategory = (id, data) => api.patch(`/asset-categories/${id}`, data);
export const getUsers = (params) => api.get('/users', { params });
export const getUserById = (id) => api.get(`/users/${id}`);
export const updateUser = (id, data) => api.patch(`/users/${id}`, data);
export const getAllocations = (params) => api.get('/allocations', { params });
export const createAllocation = (data) => api.post('/allocations', data);
export const returnAsset = (id, data) => api.post(`/allocations/${id}/return`, data);
export const getOverdueAllocations = () => api.get('/allocations/overdue');
export const getTransfers = (params) => api.get('/transfers', { params });
export const createTransfer = (data) => api.post('/transfers', data);
export const approveTransfer = (id) => api.patch(`/transfers/${id}/approve`);
export const rejectTransfer = (id, data) => api.patch(`/transfers/${id}/reject`, data);
export const getBookings = (params) => api.get('/bookings', { params });
export const createBooking = (data) => api.post('/bookings', data);
export const cancelBooking = (id, data) => api.patch(`/bookings/${id}/cancel`, data);
export const rescheduleBooking = (id, data) => api.patch(`/bookings/${id}/reschedule`, data);
export const getBookingCalendar = (assetId, params) => api.get(`/bookings/calendar/${assetId}`, { params });
export const getMaintenanceRequests = (params) => api.get('/maintenance', { params });
export const createMaintenance = (data) => api.post('/maintenance', data);
export const approveMaintenance = (id) => api.patch(`/maintenance/${id}/approve`);
export const rejectMaintenance = (id, data) => api.patch(`/maintenance/${id}/reject`, data);
export const assignTechnician = (id, data) => api.patch(`/maintenance/${id}/assign-technician`, data);
export const startMaintenance = (id) => api.patch(`/maintenance/${id}/start`);
export const resolveMaintenance = (id, data) => api.patch(`/maintenance/${id}/resolve`, data);
export const getAuditCycles = (params) => api.get('/audits', { params });
export const getAuditCycleById = (id) => api.get(`/audits/${id}`);
export const createAuditCycle = (data) => api.post('/audits', data);
export const createAuditEntry = (cycleId, data) => api.post(`/audits/${cycleId}/entries`, data);
export const getAuditEntries = (cycleId) => api.get(`/audits/${cycleId}/entries`);
export const closeAuditCycle = (id) => api.post(`/audits/${id}/close`);
export const getDiscrepancyReport = (id) => api.get(`/audits/${id}/discrepancy-report`);
export const getReportAssetUtilization = (params) => api.get('/reports/asset-utilization', { params });
export const getReportMaintenanceFrequency = (params) => api.get('/reports/maintenance-frequency', { params });
export const getReportDepartmentAllocation = () => api.get('/reports/department-allocation');
export const getReportBookingHeatmap = (params) => api.get('/reports/booking-heatmap', { params });
export const getReportAssetsDue = () => api.get('/reports/assets-due');
export const getNotifications = (params) => api.get('/notifications', { params });
export const markNotificationRead = (id) => api.patch(`/notifications/${id}/read`);
export const markAllNotificationsRead = () => api.patch('/notifications/read-all');
export const getUnreadNotificationCount = () => api.get('/notifications/unread-count');
export const getActivityLogs = (params) => api.get('/activity-logs', { params });
